services:
  db:
    image: mysql:8.2
    container_name: logme-mysql
    ports:
      - 33060:3306
    volumes:
      - logme-db:/var/lib/mysql
      - ./scripts/db/:/docker-entrypoint-initdb.d/:ro
    environment:
      - TZ=Europe/Paris
      - MYSQL_DATABASE=logme
      - MYSQL_USER=logme-user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    restart: unless-stopped

  back:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    container_name: logme-back
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - ./apps/backend/.env
    volumes:
      # - ./apps/backend:/app/apps/backend
      - .:/app
    working_dir: /app/apps/backend
    depends_on:
      - db
    command: sleep infinity

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    container_name: logme-front
    ports:
      - 5173:5173
      - 4173:4173
    volumes:
      - ./apps/frontend:/app/apps/frontend
    working_dir: /app/apps/frontend
    restart: on-failure:3
    command: sleep infinity

volumes:
  logme-db:
